# Generated by Django 4.1.7 on 2023-03-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_characters',
            field=models.CharField(choices=[('"', 'Double-quote (")'), (';', 'Semicolon (;)'), (':', 'Colon (:)'), ('^', 'Caret (^)'), ('~', 'Tilde (~)')], default='"', max_length=1),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\\t)'), ('|', 'Pipe (|)'), (' ', 'Space ( )')], default=',', max_length=2),
        ),
    ]
